name: GitHub Actions CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - githubactions*
      - feature/**
      - fix/**
      - pr/**

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "g++-13"
            os: ubuntu-24.04
            packages: "g++-13"
            toolset: "gcc-13"
            cxxstd: 11,14,17,20,2b
          - name: "clang-19"
            os: ubuntu-24.04
            packages: "clang-19"
            toolset: "clang-19"
            cxxstd: 11,14,17,20,2b
          - name: "xcode"
            os: macos-latest
            toolset: "clang"
            cxxstd: 11,14,17,20,2b
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - name: Install packages
        if: matrix.packages
        run: |
          sudo apt-get -o Acquire::Retries=3 update -y
          sudo apt-get -o Acquire::Retries=3 -y install ${{matrix.packages}}
      - name: Setup Boost
        run: |
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          LIBRARY=${GITHUB_REPOSITORY#*/}
          echo LIBRARY: $LIBRARY
          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_REF: $GITHUB_REF
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          REF=${REF#refs/heads/}
          echo REF: $REF
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          echo BOOST_BRANCH: $BOOST_BRANCH
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
          git submodule update --init tools/boostdep
          python3 tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
          ./bootstrap.sh
          ./b2 -d0 headers
      - name: Run tests
        run: |
          cd ../boost-root
          ./b2 -j3 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} variant=debug,release
